name: CI - Docker Build & Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create backend .env from GitHub Secrets
        run: |
          echo "PORT=3001" > ./tuvote-backend/.env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> ./tuvote-backend/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ./tuvote-backend/.env

      - name: Build Docker images
        run: docker-compose build

      - name: Start services
        run: docker-compose up -d

      - name: Wait for backend to be ready
        run: |
          for i in {1..20}; do
            if curl -s http://localhost:3001/api/health > /dev/null; then
              echo "✅ Backend is up!"
              exit 0
            fi
            echo "⏳ Waiting for backend... ($i/20)"
            sleep 3
          done
          echo "❌ Backend failed to start in time"
          docker-compose logs backend
          exit 1

      - name: Wait for frontend to be ready
        run: |
          for i in {1..20}; do
            if curl -s http://localhost:8080 > /dev/null; then
              echo "✅ Frontend is up!"
              exit 0
            fi
            echo "⏳ Waiting for frontend... ($i/20)"
            sleep 3
          done
          echo "❌ Frontend failed to start in time"
          docker-compose logs frontend
          exit 1

      - name: Stop services
        run: docker-compose down
